# Generated by Django 4.0.1 on 2022-06-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
